<ul class="uk-nav uk-nav-default">
    <li class="uk-nav-header">Getting Started</li>
    <li><a href="{{ url('docs') }}">Welcome</a></li>
    <li><a href="{{ url('docs/installation') }}">Installation</a></li>
    <li class="uk-nav-divider"></li>
    <li class="uk-nav-header">Basics</li>
    <li><a href="{{ url('docs/resources') }}">Resources</a></li>
    <li><a href="{{ url('docs/fields') }}">Fields</a></li>
    <li><a href="{{ url('docs/entries') }}">Entries</a></li>
    <li><a href="{{ url('docs/field-types') }}">Field Types</a></li>
    <li><a href="{{ url('docs/images') }}">Images</a></li>
    <li><a href="{{ url('docs/objects') }}">Objects</a></li>
    <li><a href="{{ url('docs/feeds') }}">Feeds</a></li>
    <li><a href="{{ url('docs/redirects') }}">Redirects</a></li>
    <li><a href="{{ url('docs/navigation') }}">Navigation</a></li>
    <li><a href="{{ url('docs/helpers') }}">Helpers</a></li>
    <li class="uk-nav-divider"></li>
    <li class="uk-nav-header">Supported Extensions</li>
    <li><a href="{{ url('docs/laramanager-blog') }}">Laramanager Blog</a></li>
</ul>